# -*- coding: utf-8 -*-
"""pitchanalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tnP2e88G9Usv0PZs6rdjUuzNywHrWvQv
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pybaseball
# %pip install --upgrade ipykernel

import pybaseball as pb
from pybaseball import statcast

import numpy as np
import pandas as pd

pb.cache.enable()

data = statcast(start_dt="2023-03-30", end_dt="2023-11-01")

test = data[['pitch_type', 'release_speed', 'release_pos_x', 'release_pos_z', 'p_throws', 'pfx_x', 'pfx_z', 'plate_x', 'plate_z']]

test = test.sort_values(by = ['pitch_type'])

pitchSet = set(['CH','CU','FC','EP','FO','FF','KN','KC','SC','SI','SL','SV','FS','ST'])

# Commented out IPython magic to ensure Python compatibility.
# %pip install Cmake
# %pip install wheel
# %pip install coincurve
# %pip install tensorflow
!pip3 uninstall --yes torch torchaudio torchvision torchtext torchdata
!pip3 install torch torchaudio torchvision torchtext torchdata

